In [1]:
import numpy  as np

1. What is a Python library? Why do we use Python libraries?

In [121]:
print('A Python library is a collection of pre-written code, functions, and modules that can be imported and used in Python programs. As the code is already  writtern it is feasible to use and at a time millions of people use at once')

A Python library is a collection of pre-written code, functions, and modules that can be imported and used in Python programs. As the code is already  writtern it is feasible to use and at a time millions of people use at once


2. What is the difference between Numpy array and List?

Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
print(f'Shape of an array is: {arr.shape}')
print(f'Size of an array is : {arr.size}')
print(f'Dimension of an array is : {arr.ndim}')

Shape of an array is: (3, 4)
Size of an array is : 12
Dimension of an array is : 2


Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
print(f'The first row of the array is {arr[0:1]}')

The first row of the array is [[1 2 3 4]]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print(f'The element at the third row and fourth column : {arr[2,3:]}')

The element at the third row and fourth column : [12]


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [30]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [58]:
mat = np.random.randint(2,size=(3,3))

print(mat)

[[1 1 1]
 [0 0 0]
 [0 1 0]]


9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [60]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.ndim

2

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [61]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
print(f'Transpose of the matrix is:')
arr.T

Transpose of the matrix is:


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1. Index wiLe multiplicatio'
2. Matix multiplication'
3. Add both the matics
4. Subtact matix B by A
5. Divide Matix B by A

In [74]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [88]:
print('Index wise multiplication:')
print(A * B)


Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [85]:
print('Matrix multiplication')
print(np.dot(A, B.T))

Matrix multiplication
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [86]:
print('Addition of both matrix')
print(A + B)

Addition of both matrix
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [89]:
print('Sustraction of matrix:')
print(B-A)

Sustraction of matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [90]:
print('Division of B by A:')
print(B/A)

Division of B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In [119]:
''' "byteswap" is a function used to swap the byte order.  for eg '''

arr = np.array([1,2,3,4])
print(list(map(hex, arr)))
print(arr.byteswap(inplace = True))
list(map(hex, arr))

['0x1', '0x2', '0x3', '0x4']
[ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744]


['0x100000000000000',
 '0x200000000000000',
 '0x300000000000000',
 '0x400000000000000']

13. What is the significance of the np.linalg.inv function?

In [111]:
'''"np.linalg.inv" is a function in numpy library is used to find the inverse of the matrix. for eg'''
A = np.array([[1,2],[5,6]])
print(A)
print('Inverse of matrix A:')
print(np.linalg.inv(A))

[[1 2]
 [5 6]]
Inverse of matrix A:
[[-1.5   0.5 ]
 [ 1.25 -0.25]]


14. What does the np.reshape function do, and how is it used?

In [112]:
'''"np.reshape" is a function in numpy library used to change the shape the np array. for eg.'''

A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Shape of matrix A : ',A.shape)
B = A.reshape(4,3)
print('After changing shape of matrix A : ',B.shape)

Shape of matrix A :  (3, 4)
After changing shape of matrix A :  (4, 3)


15. What is broadcasting in Numpy?

Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes. It works by automatically extending the smaller array to the shape of the larger array. This makes it possible to perform operations on arrays that would otherwise be incompatible.